## **DATA CLEANING**

### **1. Importing data**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
plt.rcParams["figure.figsize"] = (15,8)

In [51]:
data_df = pd.read_csv(r'F:\DataMining\dataset\bengaluru_house_prices.csv')
data_df.head()

area_type   availability            location       size  \
0  Super built-up  Area         19-Dec                 NaN        NaN   
1            Plot  Area  Ready To Move    Chikka Tirupathi  4 Bedroom   
2        Built-up  Area  Ready To Move         Uttarahalli      3 BHK   
3  Super built-up  Area  Ready To Move  Lingadheeranahalli      3 BHK   
4  Super built-up  Area  Ready To Move            Kothanur      2 BHK   

   society total_sqft  bath  balcony   price  
0  Coomee        1056   NaN      1.0   39.07  
1  Theanmp       2600   5.0      3.0  120.00  
2      NaN       1440   2.0      3.0   62.00  
3  Soiewre       1521   3.0      1.0   95.00  
4      NaN       1200   2.0      1.0   51.00

In [3]:
data_df.shape

(13320, 9)

In [4]:
data_df.columns

Index(['area_type', 'availability', 'location', 'size', 'society',
       'total_sqft', 'bath', 'balcony', 'price'],
      dtype='object')

In [5]:
data_df['area_type'].unique()

array(['Super built-up  Area', 'Plot  Area', 'Built-up  Area',
       'Carpet  Area'], dtype=object)

In [6]:
data_df['area_type'].value_counts()

area_type
Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: count, dtype: int64

In [7]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   area_type     13320 non-null  object 
 1   availability  13320 non-null  object 
 2   location      13318 non-null  object 
 3   size          13303 non-null  object 
 4   society       7818 non-null   object 
 5   total_sqft    13320 non-null  object 
 6   bath          13246 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB


**Drop những features cho rằng không dùng cho việc build model**

In [8]:
df4 = data_df.drop(['area_type','society','balcony','availability'],axis='columns')
df4.shape

(13320, 5)

In [9]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   location    13318 non-null  object 
 1   size        13303 non-null  object 
 2   total_sqft  13320 non-null  object 
 3   bath        13246 non-null  float64
 4   price       13320 non-null  float64
dtypes: float64(2), object(3)
memory usage: 520.4+ KB


## **Data cleaning: Xử lý các giá trị NA**

In [10]:
df4.isnull().sum()

location       2
size          17
total_sqft     0
bath          74
price          0
dtype: int64

In [11]:
for col in df4.columns:
    missing_data = df4[col].isna().sum()
    missing_percentage = missing_data/len(df4) * 100
    print(f'{col} has {missing_percentage}% missing data')

location has 0.015015015015015015% missing data
size has 0.1276276276276276% missing data
total_sqft has 0.0% missing data
bath has 0.5555555555555556% missing data
price has 0.0% missing data


In [12]:
x = df4.iloc[:, :-1].values

In [13]:
x

array([[nan, nan, '1056', nan],
       ['Chikka Tirupathi', '4 Bedroom', '2600', 5.0],
       ['Uttarahalli', '3 BHK', '1440', 2.0],
       ...,
       ['Raja Rajeshwari Nagar', '2 BHK', '1141', 2.0],
       ['Padmanabhanagar', '4 BHK', '4689', 4.0],
       ['Doddathoguru', '1 BHK', '550', 1.0]],
      shape=(13320, 4), dtype=object)

In [14]:
y = df4.iloc[:,-1].values

In [15]:
y

array([ 39.07, 120.  ,  62.  , ...,  60.  , 488.  ,  17.  ],
      shape=(13320,))

In [16]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
x[:,3] = imputer.fit_transform(x[:,3].reshape(-1, 1)).ravel()

In [17]:
x

array([[nan, nan, '1056', 2.6926619356786956],
       ['Chikka Tirupathi', '4 Bedroom', '2600', 5.0],
       ['Uttarahalli', '3 BHK', '1440', 2.0],
       ...,
       ['Raja Rajeshwari Nagar', '2 BHK', '1141', 2.0],
       ['Padmanabhanagar', '4 BHK', '4689', 4.0],
       ['Doddathoguru', '1 BHK', '550', 1.0]],
      shape=(13320, 4), dtype=object)

In [18]:
imputer2 = SimpleImputer(missing_values=np.nan, strategy="most_frequent")
x[:,0] = imputer2.fit_transform(x[:,0].reshape(-1, 1)).ravel()

In [19]:
x

array([['Whitefield', nan, '1056', 2.6926619356786956],
       ['Chikka Tirupathi', '4 Bedroom', '2600', 5.0],
       ['Uttarahalli', '3 BHK', '1440', 2.0],
       ...,
       ['Raja Rajeshwari Nagar', '2 BHK', '1141', 2.0],
       ['Padmanabhanagar', '4 BHK', '4689', 4.0],
       ['Doddathoguru', '1 BHK', '550', 1.0]],
      shape=(13320, 4), dtype=object)

In [20]:
imputer3 = SimpleImputer(missing_values=np.nan, strategy="most_frequent")
x[:,1] = imputer3.fit_transform(x[:,1].reshape(-1, 1)).ravel()

In [21]:
x

array([['Whitefield', '2 BHK', '1056', 2.6926619356786956],
       ['Chikka Tirupathi', '4 Bedroom', '2600', 5.0],
       ['Uttarahalli', '3 BHK', '1440', 2.0],
       ...,
       ['Raja Rajeshwari Nagar', '2 BHK', '1141', 2.0],
       ['Padmanabhanagar', '4 BHK', '4689', 4.0],
       ['Doddathoguru', '1 BHK', '550', 1.0]],
      shape=(13320, 4), dtype=object)

In [22]:
df4.isnull().sum() # becaeuse we have not updated the changes into dataset df4 

location       2
size          17
total_sqft     0
bath          74
price          0
dtype: int64

In [23]:
df4.iloc[:,0] = x[:,0]
df4.iloc[:,1] = x[:,1]
df4.iloc[:, 3] = x[:, 3].astype(float)

In [24]:
df4.isnull().sum()

location      0
size          0
total_sqft    0
bath          0
price         0
dtype: int64

In [25]:
df4.head()

location       size total_sqft      bath   price
0          Whitefield      2 BHK       1056  2.692662   39.07
1    Chikka Tirupathi  4 Bedroom       2600  5.000000  120.00
2         Uttarahalli      3 BHK       1440  2.000000   62.00
3  Lingadheeranahalli      3 BHK       1521  3.000000   95.00
4            Kothanur      2 BHK       1200  2.000000   51.00

## **Feature Engineering**

**Explore total_sqft feature**

In [26]:
def is_float(x):
    try:
        float(x)
    except:
        return False
    return True

In [27]:
df4[~df4['total_sqft'].apply(is_float)].head(10)

location       size      total_sqft      bath    price
30            Yelahanka      4 BHK     2100 - 2850  4.000000  186.000
56          Devanahalli  4 Bedroom     3010 - 3410  2.692662  192.000
81          Hennur Road  4 Bedroom     2957 - 3450  2.692662  224.500
122              Hebbal      4 BHK     3067 - 8156  4.000000  477.000
137  8th Phase JP Nagar      2 BHK     1042 - 1105  2.000000   54.005
165            Sarjapur      2 BHK     1145 - 1340  2.000000   43.490
188            KR Puram      2 BHK     1015 - 1540  2.000000   56.800
224         Devanahalli      3 BHK     1520 - 1740  2.692662   74.820
410             Kengeri      1 BHK  34.46Sq. Meter  1.000000   18.500
549         Hennur Road      2 BHK     1195 - 1440  2.000000   63.770

In [28]:
df4['total_sqft'].apply(is_float).value_counts()

total_sqft
True     13073
False      247
Name: count, dtype: int64

In [29]:
def convert_sqft_to_num(x):
    tokens = x.split('-')
    if len(tokens) == 2:
        return (float(tokens[0])+float(tokens[1]))/2
    try:
        return float(x)
    except:
        return None

In [30]:
df5 = df4.copy()
df5['total_sqft'] = df5['total_sqft'].apply(convert_sqft_to_num)
df5.head()

location       size  total_sqft      bath   price
0          Whitefield      2 BHK      1056.0  2.692662   39.07
1    Chikka Tirupathi  4 Bedroom      2600.0  5.000000  120.00
2         Uttarahalli      3 BHK      1440.0  2.000000   62.00
3  Lingadheeranahalli      3 BHK      1521.0  3.000000   95.00
4            Kothanur      2 BHK      1200.0  2.000000   51.00

In [31]:
x = df5.iloc[:, :-1].values

In [32]:
x

array([['Whitefield', '2 BHK', 1056.0, 2.6926619356786956],
       ['Chikka Tirupathi', '4 Bedroom', 2600.0, 5.0],
       ['Uttarahalli', '3 BHK', 1440.0, 2.0],
       ...,
       ['Raja Rajeshwari Nagar', '2 BHK', 1141.0, 2.0],
       ['Padmanabhanagar', '4 BHK', 4689.0, 4.0],
       ['Doddathoguru', '1 BHK', 550.0, 1.0]],
      shape=(13320, 4), dtype=object)

In [33]:
print(df5['total_sqft'].isna().sum())

46


In [34]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
x[:,2] = imputer.fit_transform(x[:,2].reshape(-1, 1)).ravel()

In [35]:
df5.iloc[:,2] = x[:,2].astype(float)

**Add new feature (Integer) for BHK (Bedrooms Hall Kitchen)**

In [36]:
df5['bhk'] = df5['size'].apply(lambda x: int(x.split(' ')[0]))

In [37]:
df5['bhk'].unique()

array([ 2,  4,  3,  6,  1,  8,  7,  5, 11,  9, 27, 10, 19, 16, 43, 14, 12,
       13, 18])

**Tạo thêm 1 feature mới => Giá trên mỗi square feet. Giả sử 100000/sqf**

In [38]:
df6 = df5.copy()
df6['price_per_sqft'] = df6['price'] * 100000/df6['total_sqft']
df6.head()

location       size  total_sqft      bath   price  bhk  \
0          Whitefield      2 BHK      1056.0  2.692662   39.07    2   
1    Chikka Tirupathi  4 Bedroom      2600.0  5.000000  120.00    4   
2         Uttarahalli      3 BHK      1440.0  2.000000   62.00    3   
3  Lingadheeranahalli      3 BHK      1521.0  3.000000   95.00    3   
4            Kothanur      2 BHK      1200.0  2.000000   51.00    2   

   price_per_sqft  
0     3699.810606  
1     4615.384615  
2     4305.555556  
3     6245.890861  
4     4250.000000

In [39]:
df6.to_csv(r'F:\DataMining\dataset\bengaluru_house_prices_version2.csv',index=False)

**Xem xét feature Location. Và áp dụng kỹ thuật giảm chiều (dimensionality reduction) để giảm số lượng Location**

In [40]:
loctation_list_counts = df6['location'].value_counts()

#### **Giảm chiều dữ liệu**
**Bất kì location nào có ít hơn 10 dữ liệu (data point) thì sẽ gán tag là "other" location. Nhằm để giảm số lượng categorical. Sau đó khi mà One Hot Encoding, nó sẽ giúp chúng ta có ít cột dummy hơn. Cụ thể: khi dummy thì mỗi giá trị categorical của location sẽ là 1 cột. Nên khi đặt như vậy sẽ giảm số lượng cột lại => sử dụng ML hiệu quả hơn**

In [41]:
print(loctation_list_counts) 

location
Whitefield                 542
Sarjapur  Road             399
Electronic City            302
Kanakpura Road             273
Thanisandra                234
                          ... 
Park View Layout             1
Xavier Layout                1
Air View Colony              1
akshaya nagar t c palya      1
mvj engineering college      1
Name: count, Length: 1305, dtype: int64


In [42]:
print(loctation_list_counts['Whitefield'])

542


In [43]:
type(loctation_list_counts)

pandas.core.series.Series

In [44]:
loctation_list_counts_less_than_10 = loctation_list_counts[loctation_list_counts<=10]

In [45]:
df6.location = df6.location.apply(lambda x: 'Other' if x in loctation_list_counts_less_than_10 else x)

In [46]:
df6.head(10)

location       size  total_sqft      bath   price  bhk  \
0          Whitefield      2 BHK      1056.0  2.692662   39.07    2   
1    Chikka Tirupathi  4 Bedroom      2600.0  5.000000  120.00    4   
2         Uttarahalli      3 BHK      1440.0  2.000000   62.00    3   
3  Lingadheeranahalli      3 BHK      1521.0  3.000000   95.00    3   
4            Kothanur      2 BHK      1200.0  2.000000   51.00    2   
5          Whitefield      2 BHK      1170.0  2.000000   38.00    2   
6    Old Airport Road      4 BHK      2732.0  4.000000  204.00    4   
7        Rajaji Nagar      4 BHK      3300.0  4.000000  600.00    4   
8        Marathahalli      3 BHK      1310.0  3.000000   63.25    3   
9               Other  6 Bedroom      1020.0  6.000000  370.00    6   

   price_per_sqft  
0     3699.810606  
1     4615.384615  
2     4305.555556  
3     6245.890861  
4     4250.000000  
5     3247.863248  
6     7467.057101  
7    18181.818182  
8     4828.244275  
9    36274.509804